### ISSUE TITLE
Mandatory Building Blocks

### ISSUE THREAD

**Issue by henkbirkholz** [sacmwg/draft-ietf-sacm-terminology#15]
The requirements draft highlights (in ARCH-005, with a lower-case “must”) the need for every _SACM Component_ to enable “announcement and negotiation of functional capabilities” and corresponding “inquiries about the capabilities of other components in the SACM ecosystem”.

If _SACM Components_ are composed out of _Building Blocks_, Announcement and Negotiation, and Query (querying & getting queried) could be considered mandatory _Building Blocks_ that MUST be part of every SACM Component. These would be Management Plane Building Blocks and corresponding definitions could be added to or extended in the terminology draft.

There might be more Building Blocks that could be Mandatory Building Blocks.

**Comment by adammontville** [comment]
Do we need to define "mandatory building blocks" or is it enough for such requirements to be implied in respective drafts with appropriate language (i.e. MUST)?  If so, this seems like it might become an issue for the architecture draft.

**Comment by henkbirkholz** [comment]
removed building blocks.
