### ISSUE TITLE
Processed Attributes

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-terminology#17]
I want a better term than processed attributes that is defined in this document for referencing from the architecture draft.  This concept includes the ideas of transforming attributes, combining attributes together to produce new attributes.  Just about anything one can think of EXCEPT for the process of doing an evaluation?

**Comment by adammontville** [comment]
I'm not finding the term "processed attributes" in https://www.ietf.org/id/draft-ietf-sacm-terminology-07.txt, are you looking somewhere else or has this issue been addressed?

**Comment by jimsch** [comment]
As stated in my original comment - that term is currently in the architecture draft and a better version of it needs to be here and so that it can be 'referred to" from that draft.

**Comment by adammontville** [comment]
Closing this because there isn't an architecture draft to speak of any more.
