### ISSUE TITLE
Software package, software component, software instance

### ISSUE THREAD

**Issue by llorenzin** [sacmwg/draft-ietf-sacm-terminology#18]
During the requirements working session this morning, we discussed the difference between a software component and a software instance, which are defined in the information model but not (yet) in the terminology draft.  Looking more closely at the information model, I think there is still some clarification required here.  

My initial impression was that a "software component" is a software package installed on an endpoint, with a unique serial number (i.e. Microsoft Word 2013, product ID $foo) and a "software instance" is a running instance of the software component (i.e. one logged-in user has one instance and another logged-in user has another instance).

However, upon re-reading the definitions in information model section 4.2, it seems to indicate that a "software component" is the _generic_ software package (i.e. Microsoft Word 2013) and a "software instance" is the software package installed on the endpoint with the unique serial number (ie.e Microsoft Word 2013, product ID $foo).  Is that the intent?  If so, then my previous understanding (up to and including this morning's requirements session) was incorrect, and it seems like a confusing use of the term instance.

I propose we consider creating three separate terms here:

Software package: a _generic_ software package (i.e. Microsoft Word 2013) 
Software component: a software package installed on an endpoint, including a unique serial number if present (ie.e Microsoft Word 2013, product ID $foo) 
Software instance: a running instance of the software component (i.e. on a multi-user system, one logged-in user has one instance of Word running and another logged-in user has another instance of Word running, or on a single-user system, a user could have multiple independent instances of a single software component running).

The information model currently says that a software component can be an asset, and it does not say whether a software instance can be an asset.  If we use the three definitions above, I believe we need state that both a software package and a software component instance can be an asset.  (For example, an audit may require identification of software packages _and_ their unique serial numbers to ensure that serial numbers are not re-used across multiple machines.)  I don't have an opinion one way or the other on whether a software instance is also an asset.

**Comment by sacm** [comment]
Hi,

+1 to Lisa's definitions of software package/component/instance.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Winter  579 Park Place  Saline, MI  48176  734-944-0094
Summer  PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by adammontville** [comment]
I think I like these definitions.  Would this definition of software package permit composition, such that one software package could be comprised of others?

**Comment by jimsch** [comment]
A software package would definitely permit composition.  Office could be composed of Word, Excel,... each as independent packages.  The more interesting question is what happens with a composite package that is installed.  Are software components composible?   Does one have a software component that matches Office?  Or are the components only Word, Excel,...?   The latter would imply that not all software packages can have components.  The former that the composition needs to be looked at from both of the levels.   I don't think this is an issue for instances as there would always be a one-to-one correspondence between instances and components.

**Comment by henkbirkholz** [comment]
Addressed in the draft, leaving this open for final comments.
