### ISSUE TITLE
Data Origin

### ISSUE THREAD

**Issue by henkbirkholz** [sacmwg/draft-ietf-sacm-terminology#26]
Quote: "One or more properties that enable a SACM component to identify the SACM component that initially acquired or produced data about a (target) endpoint (e.g. via collection from a data source)."

There might be a too strong focus on the SACM Task "Information Collection"/"Collection" here. What about SACM content that is not initially acquired or produced by a target endpoint, e.g. "assessment"/"evaluation result"?

This issue is related to Issue https://github.com/sacmwg/draft-ietf-sacm-terminology/issues/17 "Processed Attributes".

**Comment by adammontville** [comment]
Note to revisit this entire definition.
