### ISSUE TITLE
define metadata

### ISSUE THREAD

**Issue by djhaynes** [sacmwg/draft-ietf-sacm-terminology#36]
We need to provide a definition for metadata in the Terminology I-D.

**Comment by sacm** [comment]
Hi Danny,

From Merriam-Webster dictionary:

"data that provides information about other data"

From Oxford dictionaries:

"A set of data that describes and gives information about other data"

From Internet Security Glossary v2 (RFC 4949):

"Descriptive information about a data object; i.e., data about data, or
data labels that describe other data"

Note that RFC 4949 goes on to say that "metadata" (without hyphen)
was a US registered trademark of The Metadata Company - granted
in 1986 (although the first use of the unhypenated word was 1981).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Winter  579 Park Place  Saline, MI  48176  734-944-0094
Summer  PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by djhaynes** [comment]
Thanks Ira.  Does the note about RFC 4949 and "metadata" being a registered trademark cause concern for us then?

**Comment by henkbirkholz** [comment]
Included in draft text. The conclusion was to be unconcerned.
