### ISSUE TITLE
Update reference to vulnerability scenario

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-terminology#38]
The draft appears to presently say: "A prominent instance of the assessment workflow is illustrated in the Vulnerability Assessment Scenario [I-D.ietf-sacm-vuln-scenario]." The reference should point to the wiki or use another description.

**Comment by henkbirkholz** [comment]
I am hesitant to favor a wiki page (which can go away or change drastically in its semantic context and therefore is more ephemeral) in contrast to an I-D, which might expire, but will always be an available immutable resource.

What does the group think?

**Comment by jarrettlu** [comment]
Hi Adam,

I also favor referencing a draft, or an alternate stable document, rather
than a wiki page. What problem do you see and try to address?

Jarrett

**Comment by adammontville** [comment]
The vulnerability draft will not progress. We decided to go to a wiki. If
you want to reference a draft that has, or will eventually, expire that's
up to you.
