### ISSUE TITLE
Should "Collection Method" be pulled out from "Collection Task"

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-terminology#40]
The current definition for _Collection Task_ includes a description of three collection methods. Would folks be opposed to explicitly defining _Collection Method_?

**Comment by henkbirkholz** [comment]
Agreed.

On my personal task list is "acquisition-type".

We are considering to split out "types of frequency" to be included in ""acquisition-type", pulling the terms "freshness" (derived from RFC4949 "fresh") in, so we can define "interval" to better refer to YANG push terms, such as "periodic", "on-change", and "dampening".
