### ISSUE TITLE
Thoughts on "Data Origin"

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-terminology#41]
The way our definition for _data origin_ is written makes it seem like the origin of data is a set of endpoint attributes (while creating a synonym for endpoint attributes in "properties"). This does not feel accurate. The _data origin_ is _the SACM component that initially acquired or produced data about an endpoint_. We may call that SACM component the _originating SACM component_. Then we an use the last sentence of the existing definition: _Data Origin can be expressed by an endpoint label information element_. Although, that feels more complicated than is necessary and we may instead want to say something like: _Data Origin is represented by one or more endpoint attributes intended to identify the originating SACM Component_.

**Comment by henkbirkholz** [comment]
If there are no objections, I will include the proposed change.

**Comment by adammontville** [comment]
Thanks, Henk. There is a similar circumstance for _Data Source_ which is also written in a manner suggesting that the source is a set of endpoint attributes. Can we add that fix to this issue also?

**Comment by henkbirkholz** [comment]
No objections here also.

**Comment by djhaynes** [comment]
Both updates seem reasonable to me.

Thanks,

Danny
