### ISSUE TITLE
Please have "Endpoint Characterization" use "Endpoint Characteristic" in its definition

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-terminology#44]
The draft presently defines _Endpoint Characterization_ as a composition of _endpoint attributes_, and makes no mention at all of _endpoint characteristic_. Is this intentional? Are _endpoint attributes_ and _endpoint characteristics_ synonymous? If so, can we pick one and stick with it?

**Comment by henkbirkholz** [comment]
This is a good question. They are already very similar. We should check RFC4949 and resolve the question soon. I will have a look at it.
