### ISSUE TITLE
Revisit "Endpoint Label"

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-terminology#46]
The term _Endpoint Label_ indicates that these are for endpoints, but then describes them as being applied to SACM components as well. I do not believe that a SACM Component is an endpoint, is it? Also, the "endpoint label" seems like an authoritative (in a SACM Domain) identifier. True? If so, then we should state that perhaps more clearly.

**Comment by henkbirkholz** [comment]
A SACM component is not a "target endpoint". Both SACM components and target endpoints are typically endpoints (NEA: endpoint, RFC4949: information system or system entity, respectively).

A label is intended to refer to an endpoint regardless of its "role" or being a target endpoint. SACM component label and target endpoint label would be taxonomic specializations.

In any case, we should state that more clearly.

**Comment by henkbirkholz** [comment]
Addendum: *by default*, a SACM component is not a target endpoint, because it is an excluded endpoint. You can deviate from that default in a SACM domain via corresponding imperative guidance.

**Comment by adammontville** [comment]
Henk, a "target endpoint" is an endpoint. How is an "excluded endpoint" not an endpoint? Probably my mistake, but you're still saying it's an endpoint?

**Comment by henkbirkholz** [comment]
Both excluded endpoints and target endpoints are endpoints, of course....

It either is included in continuous monitoring, or not.
