### ISSUE TITLE
"Endpoint Management Capabilities" 

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-terminology#47]
Earlier _Asset Management_ is described as a process concerning asset lifecycles. The present definition for _Endpoint Management Capabilities_ seems to describe the process concerning at least a portion of the endpoint lifecycle. Should we consider renaming this term and/or updating the definition, such that it has a similar structure to that of _Asset Management_?

**Comment by henkbirkholz** [comment]
"Endpoint Management Capabilities" is a term pulled in from the Vulnerability Assessment Scenario. If you want to rename that term (which includes a few redundancies an has a somewhat vague scope), the authors of the Vulnerability Assessment Scenario draft should chime in here, I think.

**Comment by djhaynes** [comment]
I agree "asset management" covers some of this, however, I wonder if we can just leave the term as-is :) since we spent some time coming up with it. If we do make any changes, I think I would prefer an update to the definition rather than changing the name of the term.

Thanks,

Danny
