### ISSUE TITLE
Proposed update to definition for "Evaluation Task"

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-terminology#48]
Propose: A task by which an endpoint's asserted attribute value is evaluated against an expected attribute value.

**Comment by henkbirkholz** [comment]
We discussed the term evaluation a lot between authors.

What would the group think if we collapse the term evaluation into assessment (making Evaluators Asserters respectively)?

**Comment by djhaynes** [comment]
I don't think I have an objection. If I remember correctly, we originally chose "evaluation" because  we thought there could be other types of evaluation, however, I am not sure those are critical at this point. 

Thanks,

Danny

**Comment by adammontville** [comment]
I've been working with the understanding that assessment consists of collection and evaluation. In fact, the definition for assessment says as much. Then, why would collapsing evaluation into assessment help? The evaluation is still looking at an actual (at least an asserted) value and comparing that against an expected value, which is all my proposal suggested - just to be a little more specific in describing what an evaluation is.

**Comment by djhaynes** [comment]
I think your updated text for "evaluation task" would be a good improvement.
