### ISSUE TITLE
Thoughts on "SACM Function"

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-terminology#53]
I'm struggling with this term because by my read it's attempting to narrow a common definition of "function" (in computer science terms) to something that reads more like the description of "capability".  A "capability" is the extent of something's ability, and, for example, the following reads more like the description of a capability than a function: `For example, a SACM function with interfaces on the control plane can provide a brokering function to other SACM components.`

Would we be better off striking this term and relying on "capability" instead?

**Comment by sacm** [comment]
Hi,

I agree with Adam here.  This overloading of "function" when a "capability"
is actually the example is confusing.

Cheers,
- Ira


Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Jan-April: 579 Park Place  Saline, MI  48176  734-944-0094
May-Dec: PO Box 221  Grand Marais, MI 49839  906-494-2434
