### ISSUE TITLE
Should SACM scope statements belong in the terminology draft?

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-terminology#64]
For Data In Motion we say, "The SACM architecture and corresponding models focus on data in motion."

For Data At Rest we say, "In the context of SACM, data models for data at rest are out of scope."

Do we really need either of these statements in the terminology draft? They seem out of place.

**Comment by henkbirkholz** [comment]
It is true that scope is not defined in this document. Also, explanatory (con)text should help and not confuse.

In consequence, I would raise the question: Is it useful to reiterate the association with scope as explanatory (con)text, or is it confusing?

**Comment by david-waltermire** [comment]
The charter defines what is in scope for an IETF WG. Any mention of scope should be left to the SACM charter.

Regards,
Dave

**Comment by henkbirkholz** [comment]
The charter text does neither include date in motion nor data at rest. How would you resolve the disconnect between definition and scope, Dave?

Also, when the WG is closed, a definition, what the scope the created set of RFC (i.e. the scope of the contributions, not the scope of the WG) will have, should remain in at least one document. Where would you retain that information, Dave?

**Comment by david-waltermire** [comment]
If the charter does not state something as out of scope, it is typical that the thing is considered within scope. From a process perspective, it’s up to the WG chairs to sort out scope issues if needed.

I don’t think it’s necessary to retain information about the scope of the WG. Each published RFC should articulate the scope of what it is defining. If cross RFC or architectural concerns need to be defined, then an architecture draft should speak to such concerns.

**Comment by henkbirkholz** [comment]
I agree that we do not need to retain WG charter scope.

That is why I tried to highlight "scope of resulting solutions".

In the end, there will be a set of proposed standards, a few of them informational. Imagine, the reader for example being an engineer of a vendor, I would like to know the intend and applicability of these proposed standards to my products and business strategy. Effectively, I would like to know if I can just use any data at rest representation I want, or if there are some imposed prescribed restrictions wrt the characteristics of how I store processed content in a repository - and there are none.

This is the only reason why the text is in the definition. If this violates an exclusiveness that is tied to the context of the charter, we just have to rephrase it and/or put that information in another document. If not, maybe just keep it.

**Comment by adammontville** [comment]
I would propose that we remove "The SACM architecture and corresponding models focus on data in motion" from the definition of Data In Motion; I also proposed that we remove "In the context of SACM, data models for data at rest are out of scope" from the definition of Data At Rest.

**Comment by jarrettlu** [comment]
I second Adam's proposal about removing term Data In Motion from the terminology draft. It could appear in an architecture draft when appropriate. I also agree on removing the "data at rest" sentence, which appears to belong to a information/data module draft.

**Comment by adammontville** [comment]
Jarrett, just to be clear, my proposal was to remove the quoted sentences concerning scope. But, because your second mentions it... Should we define data in motion and data at rest at all? Wouldn't this be a bit like defining network address (see #89 ).

**Comment by henkbirkholz** [comment]
Okay, I have to chime in here. The problem with our past "role" definition was that it was mixing two scopes:

1. roles that define the interaction on the data plane
2. roles that define the function inside a sacm component

The first is a role involving (amongst other things) data in motion - we are prescriptive about that to some extend as we will select/define a common data model for interaction between sacm components on the data plane (data in motion).

The second is a role about (among other things) data at rest - we are not prescriptive about that, but provide the semantics what is supposed to happen "inside" a sacm component (e.g. a repository).

As we could not find existing standards or specifications that we could use as a reference, we defined the term data in motion and data at rest ourselves a long time ago. If this has changed, we can just refer to the source definition in an architecture document. If there is none, I think we avoid a lot of imprecision by just defining them. I totally agree with removing any expositional text wrt to scope or charter.

To reiterate, I would prefer to point to a exiting definition if it is stable and available.
