### ISSUE TITLE
Proposal to remove the input/output details from definitions

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-terminology#68]
Several of our terms, such as *SACM Component Discovery* include some indication of what input and output they would expect. Such information seems very much out of place in a terminology definition.

Are input/output items pertinent to the definition of a term?

**Comment by henkbirkholz** [comment]
Agreed. I think they should go into the architecture. Also, we probably need more running code to refine the understanding of their "scope" (I do not mean WG scope!).

**Comment by adammontville** [comment]
Addressed in branch `no-label-issues` (to be sync'd soon)
