### ISSUE TITLE
Propose to remove Target Endpoint Characterization

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-terminology#74]
We have already talked about "Endpoint Characterization" and "Target Endpoint" is it really necessary to define the combination of the two? Or, does this jive with that?

**Comment by henkbirkholz** [comment]
This is an oversight. The term "Endpoint Characterization" is always about target endpoints and should be renamed to "Target Endpoint Characterization".

**Comment by adammontville** [comment]
Ok, then the definition would be changed to ```The description of the distinctive nature of a target endpoint, that is based on its characteristics``` from ```The description of the distinctive nature of an endpoint, that is based on its characteristics.```

**Comment by adammontville** [comment]
Addressed in branch `no-label-issues` (to be sync'd soon)

**Comment by henkbirkholz** [comment]
Only Target Endpoints have to be classified, not every endpoint.

Edit: Sorry, I meant Characterization, but it is true for both.

**Comment by henkbirkholz** [comment]
In general Classification and Characterization is only required for Target Endpoints. Labels can be used for every endpoint, including SACM Components. Does that clarify the issue a bit?

I.e. my proposal is roughly this: keep terms including "Target" wrt Classification and Characterization & keep the three terms Endpoint Label, Target Endpoint Label and SACM Component Label.
