### ISSUE TITLE
Propose to remove Target Endpoint Label

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-terminology#79]
We have already talked about "Endpoint  Label" and "Target Endpoint" is it really necessary to define the combination of the two?

**Comment by henkbirkholz** [comment]
If the concept Target Endpoint Label is dropped, we loose the object property relationship to data source in content metadata. Also, this term is an example of the indicated specialization in Endpoint Label (in the definition of Endpoint Label) similar to SACM Component Label. Both highlighted examples have Endpoint Label as their taxonomic parent, which makes sense and simplifies/homogenizes how "known things" are referenced in a SACM domain by not using the complete Target Endpoint Identifier (which can become quite big at times) all the time, but using the same label mechanism everywhere.

**Comment by adammontville** [comment]
Ok, then from your perspective this is a necessary term. Then, I would propose an update to the definition where Target Endpoint Label ```is an endpoint label that identifies a specific target endpoint``` and call it good. Thoughts?

**Comment by adammontville** [comment]
Addressed in branch `no-label-issues` (to be sync'd soon)
