### ISSUE TITLE
Either remove or actually define Virtual Component

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-terminology#81]
I feel like we should remove this term. Either that, or we need an actual definition, as what currently exists is a related, but non-definitional, statement:

> A target endpoint can be composed entirely of logical system entities (see RFC4949).

That is not a definition, but perhaps a characteristic of a target endpoint.

**Comment by henkbirkholz** [comment]
If I remember correctly, the consensus was to include virtual "components", but I think the meaning behind this was things, such as virtual machines or virtualized network functions. Charles might remember more about this, as we had a long round table discussion on this with him present.

A quick hotfix: relabel to Virtual Endpoint and change definition to: "An endpoint composed entirely of logical system components (see RFC4949)." Some context and explanatory text is still required, but that should address the biggest issues ad-hoc, I think.

**Comment by adammontville** [comment]
Addressed in branch `no-label-issues` (to be sync'd soon)
